version: "3.7"

services:
    hashtag:
        build: .
        container_name: hashtag
        ports:
            - "5003:5000"
        volumes:
            - .:/usr/src/app
        environment:
            PYTHONUNBUFFERED: 1

            FLASK_APP: app.py
            FLASK_ENV: development
            FLASK_RUN_HOST: 0.0.0.0

            DB_TYPE: postgresql
            DB_DRIVER: psycopg2
            DB_USER: root
            DB_PASSWORD: root
            DB_HOST: db
            DB_NAME: hashtag

            TEST_DATABASE_URI: sqlite:///database.db

            KEY: ${KEY}
            JWT_ALGORITHM: ${JWT_ALGORITHM}
            JWT_SECRET: ${JWT_SECRET}
        depends_on:
            - db

    db:
        image: postgres
        container_name: hashtag_db
        ports: 
            - "5435:5432"
        volumes: 
            - ./data/db:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: hashtag
